### ISSUE TITLE
iBeacons

### ISSUE THREAD

**Issue by jerone** [xamarin/mini-hacks#25]
In the post from Xamarin Blog there's an article about [iBeacons](https://blog.xamarin.com/ibeacons-everywhere/), which reference multiple times to this repo. 
But apparently that branch has been removed as it creates 404's. 

Is it possible to restore that branch or update that article with another branch?

**Comment by rlingineni** [comment]
+1

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
